# Generated by Django 3.2.2 on 2022-06-11 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20220610_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='user_auth.doctor'),
        ),
    ]
