# Generated by Django 3.2.2 on 2022-06-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_doctor_rejected_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='rejected_message',
            new_name='status_message',
        ),
    ]
