# Generated by Django 3.2.2 on 2022-05-03 17:49

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='file',
            field=models.FileField(default='/default_images/default_image_for_all_models.jpeg', upload_to=web.models.Discussion.upload_discussion_file),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='image', max_length=5),
        ),
        migrations.DeleteModel(
            name='DiscussionFile',
        ),
    ]
