# Generated by Django 3.2.2 on 2022-05-07 17:25

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_comment_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=web.models.Discussion.upload_discussion_file),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('application', 'Application')], default='image', max_length=12),
        ),
    ]
